### ISSUE TITLE
Math formulas don't render properly in the documentation

### ISSUE THREAD

**Issue by RemiLehe** [LASY-org/lasy#145]
When visiting this page:
https://lasydoc.readthedocs.io/en/latest/api/profiles/transverse/gaussian.html
I get this rendering:
<img width="312" alt="Screenshot 2023-05-22 at 10 01 27 AM" src="https://github.com/LASY-org/lasy/assets/6685781/29a3e2d7-4035-4be2-9885-6e5d892eb25e">
Is this specific to my browser/setup?

**Comment by AngelFP** [comment]
I just had a look at the readthedocs history. Paradoxically, it seems that the problem was introduced in #120 😅. I'll try to find out the reason.

**Comment by AngelFP** [comment]
Fixed in #146
