### ISSUE TITLE
Having more than one Laguerre-Gaussian mode.

### ISSUE THREAD

**Issue by JessicaTiebel** [LASY-org/lasy#224]
Hi
Is it possible to add several transverse Laguerre-Gaussian modes to a Laser profile?

**Comment by JessicaTiebel** [comment]
OK I figuered out, that the `Profile` class has an `__add__` function which is inherited by the `CombinedLongitudinalTransverseProfile` class and basically does what I was asking for. But unforntunately the laser_energy information of the single profiles I combine is lost during that process. Is there an intended way to restore  or keep this information?

**Comment by rob-shalloo** [comment]
Hey Jessica,

When combining the pulses you can also take advantage of the `__mul__` and `__rmul__` operators which allow you to multiply or scale the profile by a scaler. This would allow you to control the relative contribution of each LG pulse. Then reset the energy for the total pulse.

Another option is that very recently I added the same `__add__`, `__mul__` and `__rmul__` overload operators to the `TransverseProfile`. This should make the calculation much quicker. Again you would use the multiply option to scale the relative contribution of each profile, then add them all together. The laser energy would then be set when defining the `CombinedLongitudinalTransverseProfile`

**Comment by JessicaTiebel** [comment]
Thanks for the answer!
