### ISSUE TITLE
Support for user-defined/one-off longitudinal and transverse profiles

### ISSUE THREAD

**Issue by kale-j** [LASY-org/lasy#233]
I'd like to be able to set up custom longitudinal and transverse profiles for one-time use. I would think the best way to do this would be something akin to

```py
from lasy.profiles.longitudinal.longitudinal_profile import LongitudinalProfile

class CustomLongitudinalProfile(LongitudinalProfile):
...
```
Then CustomLongitudinalProfile could be used in the same way as the pre-defined profiles.

However, as far as I can tell, the base class LongitudinalProfile hasn't been included in what the user can access. 
Is there a reason for this? Any better way to do what I'm trying to do?

**Comment by RemiLehe** [comment]
Fixed by #237
