### ISSUE TITLE
Best geometry for FBPIC

### ISSUE THREAD

**Issue by koesterf** [LASY-org/lasy#283]
Hi,

which geometry is the best for saving data and later loading it in FBPIC code ?

```  rt ``` or ``` xyt ```

Thanks
Frank

**Comment by RemiLehe** [comment]
Hi,

Thanks for the question.
I think it makes more sense to save the data in `rt` format, since FBPIC assumes close-to-cylindrical symmetry anyway, and since `rt` files are smaller than `xyt` files.

**Comment by koesterf** [comment]
Hi @RemiLehe,

Thanks a lot. 
F.
