### ISSUE TITLE
Spectral input mode: pulse-length dependence on sample points?

### ISSUE THREAD

**Issue by n01r** [LASY-org/lasy#298]
Hi,

I recently wanted to use the measured spectral intensity of a laser pulse (intensity vs wavelength) to create a temporal pulse shape. I came across some behavior that could potentially be a bug.

The measurement was in arbitrary units, so there is background, except for one or two data points at the end of the range. I removed this (because otherwise this will very obviously affect the pulse length) and shifted the whole signal so the bottom of the pretty flat background is zero. The signal itself is roughly super-Gaussian-shaped and is clearly distinct from the background. 

@aodhanmci, are there issues with possibly posting a screenshot of the raw data?

I then put this into `LongitudinalProfileFromData`
```Python3
    # Create corresponding laser profile, by combining
    # a longitudinal profile defined by the above spectral info
    # and a transverse Gaussian profile
    long_profile = LongitudinalProfileFromData(
        {'datatype': 'spectral',
         'axis': lambda_range,
         'intensity': intensity,
         'phase': phase,
         'dt': (hi[-1] - lo[-1]) / num_points[-1]},
        lo=lo[-1],
        hi=hi[-1])
```

I found that the pulse that came out was unexpectedly sharp. So, I chose a window and set everything around the signal to zero. I also limited the total length of the input array. Both variations already seem to influence the pulse individually.
In the plot below, the numbers are <bandwidth (nm) > | < radius around the central frequency (nm) beyond which signal is set to 0 >
<img width="566" alt="image" src="https://github.com/user-attachments/assets/0ab14971-cd77-43c3-948c-af64c17acf17">

I cross-checked and used an analytical Gaussian input. It barely changes the pulse length except when I cut off the signal too close around the peak (blue line, cut off at 20% signal maximum)
<img width="576" alt="image" src="https://github.com/user-attachments/assets/af820398-5c1d-41a0-bd50-b24ae3160ca5">

- If you cut off the signal substantially (at 20% height at 20nm radius around the peak) you significantly change the pulse shape (expected - that's what should happen)
- Green and orange coincide, meaning that we do not see the same change in shape based on changing the number of sample points and bandwidth while keeping the non-zero signal the same
- Red and violet coincide, meaning that the Gaussian falls off fast enough that 105nm of non-zero signal is absolutely enough to capture all the necessary non-zero signal 

I then checked what happens if I resampled the Gaussian and increased the number of sample points
<img width="566" alt="image" src="https://github.com/user-attachments/assets/532fa4f8-1fb8-4c9f-9e3e-1a9fa8cfc5fe">

- Resampling the area of interest in the spectral intensity (10000 points interpolating the original spectrum between 750 and 860 nm) shows that it only smoothes the pulse but does not change the pulse length 

Perhaps I overlooked something, but I thought it warranted a closer look at what happens in LASY.

**Comment by n01r** [comment]
Hi @rob-shalloo, I will try to provide a simple reproducer script.
However, my tests with an analytical Gaussian pulse do not show the issue, indicating that this pulse shape is either too benign or I made a mistake in eliminating the background and normalizing the measured spectrum.

**Comment by rob-shalloo** [comment]
Hey @n01r ,the background subtraction could indeed be the issue, but I'd be happy to take a look for you whenever you have the reproducer script. If there's data associated with your script, then you're also welcome to email directly, if you prefer.

**Comment by rob-shalloo** [comment]
Hey @n01r ,the background subtraction could indeed be the issue, but I'd be happy to take a look for you whenever you have the reproducer script. If there's data associated with your script, then you're also welcome to email directly, if you prefer.

**Comment by n01r** [comment]
Hi @rob-shalloo, the background might really be the issue. I looked at it in detail again, and LASY might in fact have nothing to do with this. There is also a no-signal measurement that I can use to subtract background and I'll play around with that to see if the issue still persists or if I can close it.

**Comment by n01r** [comment]
I'm closing the issue because I think the problem was on my side.

The background, even after subtracting it with a background measurement had a plateau-ish shape over the whole wavelength range. This was 3 orders of magnitude below the main signal. I had expected this to not contribute a lot but since it does look like a constant signal it basically all adds to the Fourier-transformed signal at time = 0. That makes the pulse very sharp.

A window function helps and it is just left to discuss between experimentalists and theoreticians what the best drop-off should be at the region where the signal goes into noise. This has a slight effect on the pre-pulse structure some 3-5 orders of magnitude below the laser peak and some 100s of fs out. That can be relevant but has nothing to do with LASY itself.
