### ISSUE TITLE
Make `t` the slowest varying index, in 3D meshes?

### ISSUE THREAD

**Issue by RemiLehe** [LASY-org/lasy#51]
When reading the data from a lasy-produced file, a full PIC code might want `t` to be slowest-varying variable, since it will be taking slices at fixed `t`, to feed the laser antenna.

Therefore, we might consider storing the laser field already in this format, in the openPMD file.

**Comment by MaxThevenet** [comment]
This has been addressed, the current conversions from internal representation to openPMD file is clarified in #105.
