### ISSUE TITLE
1D Complex Temporal Profile, e.g., FROG data

### ISSUE THREAD

**Issue by MaxThevenet** [LASY-org/lasy#60]
This is a longitudinal profile: get the complex longitudinal envelope (both amplitude **and** phase) from FROG measurements.

**Comment by rob-shalloo** [comment]
Can you update the title of this issue to remove FROG? This is just one method of measuring the temporal profile of a pulse. I think the solution should be more general

**Comment by ax3l** [comment]
Agreed, and ideally we can also read FROG-formatted data directly :)
